# Generated by Django 4.0.3 on 2022-03-26 10:33

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(blank=True, default='posts/default.jpg', null=True, upload_to=user.models.upload_to),
        ),
    ]
