version: '3.10'

services:
  db:
    container_name: pgdb
    image: postgres
    env_file:
      - ./api/instagram/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    links:
      - db:db
    env_file:
      - ./api/instagram/.env
    ports:
      - 5050:80
volumes:
  postgres_data:
